Channel.hpp, Client.hpp, Server.hpp
=> [Add] : chnnel, client, server class

Client.cpp, Client.hpp, Command.cpp, Command.hpp
client 클래스에 setter추가, pass, nick, user 커맨드 사용 여부 플래그 추가 / Command 클래스추가
=> [ADD] : add setter in Client, add the Command class

Channel.cpp, Channel.hpp, essential.hpp
[Add] Channel.cpp 추가 및 구현 (자세한 내용과 반환값들은 주석으로 표시했습니다.)
[Mod] Channel.hpp 정의 추가
=> [Add] Channel.cpp 추가

Channel.cpp, Channel.hpp
- kick()에 reason 매개변수 추가
- 각 함수 호출 시 메세지 알맞는 버퍼에 보내기
- join() 할 때 new_client의 joined_channel 리스트에 추가
=> [Mod] kick() reason 추가, 각 함수의 메세지 set 추가

Client.hpp, Makefile, Server.cpp, Server.hpp, essential.hpp, handleresponse.cpp
[Mod] 의미 없는 const 삭제
[Mod] 서버 객체 이름 추가, essential.hpp에 servername 전역 변수 선언
=> [Add] handlereponse 파일 추가 등

essential.hpp, handleresponse.cpp
[Mod] handleResponse 함수명도 잘 못 되어 있었습니다..
=> [Mod] error replies, command responses 기존에 없던 메세지 형식 추가

Server.cpp, handleresponse.cpp, main.cpp
=> [Mod] kevent error

Channel.cpp, Command.cpp
현재 서버 동작과 유저 등록 + 채널의 TOPIC, JOIN까지 구현 완료.
MODE 관련 파싱 수정 필요
=> [Mod] bug fix (JOIN, TOPIC)

Channel.cpp, Channel.hpp, Command.cpp, handleresponse.cpp
- `messageFormat()`의 PRIVMSG 형식 마지막에 "\r\n" 추가
- Channel class에 `broadcastWithoutClient()` 함수 추가
- Command class에 PRIVMSG에서 `broadcastWithoutClient()` 호출하도록 변경
- `Channel::kick()` 메세지 마지막에 "\r\n" 추가
- `Channel::kick()' 마지막 줄 request_client를 target_client로 변경
- `Command::kick()`의 command를 comment로 이름 변경
- MODE 파싱
- KICK 강퇴반사 문제
- INVITE
=> [Mod] 6/8 bug fix

Channel.cpp
=> [Mod] message error fix

Channel.cpp, Command.cpp
findClient에서 널포인터일때 처리안한 부분 있어서 처리함, mode도 수정
=> "[MOD] : kick segmentation fault fix"

Channel.cpp, Channel.hpp, Server.cpp
채널 만들었을 때 사용자가 op인지 아닌지 출력이 잘못되는 오류를 수정했습니다.
=> [Mod] fix JOIN op message error

handleresponse.cpp
=> [MOD] : join message fix

Channel.cpp
key가 설정되어 있을 때 key를 다시 설정할 수 있도록 수정했습니다.
=> [Mod] enable to set key again

Channel.cpp
=> [Mod] Channel.cpp 옵션 설정 메세지 제거

Command.cpp, essential.hpp, handleresponse.cpp
[ADD] : add message Command::mode()
=> [ADD] : add message Command::mode()

Channel.cpp, Channel.hpp, Command.cpp, Server.cpp
- opt_k 기능 구현
- opt_l 기능 구현
- JOIN 오류 매개변수 추가
- checkAuthority() public 영역으로 옮김
- MODE 바뀐 공지 잘 설정 됐을 때만 나오게 수정
=> [Mod] MODE 버그 수정

Bonus.cpp, Bonus.hpp, Client.cpp, Client.hpp, Command.cpp, Command.hpp, Server.cpp
- 개인 메세지 안보내지는 문제 해결
- NICK 중복시 메세지 꼬이는 문제 해결
- send error시 프로그램 꺼지지 않고 disconnect하게 수정
- bonus bot 구현
- ERR 451 제거
- 마지막 client가 나가면 (kick, quit, errorquit) 채널 삭제되게 수정
- KICK + 없는 닉네임 오면 seg fault 나오는 문제 해결
- 가끔 클라이언트 연결 끊기거나 서버 프로그램 종료할 때 seg fault 나오는 현상
=> [Mod] 6/11 jaejilee 문제 해결 종합

Client.cpp, Client.hpp, Command.cpp, Server.cpp, Server.hpp, essential.hpp, handleresponse.cpp, main.cpp
- 서버 비밀번호 잘못 입력시 그 소켓의 연결을 끊어주게 구현
- 멤버변수 disconnect를 읽고 disconnect를 해주게 구현
- 잘못된 비밀번호 입력시 전송하는 핸들링 메시지 추가
=> [Mod] client disconnect멤버 변수 추가, 잘못된 비밀번호 문제 해결, 핸들링 메시지 추가

Channel.cpp, handleresponse.cpp
- operator 아닌 오류 프로토콜 수정
- 없는 유저에 대한 오류 프로토콜 수정
=> [Mod] fix operator message bug

Channel.cpp, handleresponse.cpp
=> [Mod] fix INVITE protocol

Server.cpp, main.cpp
클라이언트가 ctrl + c 혹은 그와 유사하게 종료된 경우 서버에서도 이를 감지할 수 있게 수정
=> [Mod] 클라이언트의 연결이 끊겼을 때 서버에서도 지워주게 수정

Channel.cpp
=> [Mod] channel kick errmsg

Channel.cpp
Channel.cpp에 있는 handleResponse 매개변수 부족한 것들 모두 채움
=> [Mod] fix Channel.cpp parameter error

Channel.cpp
=> [Mod] fin channel topic set

Command.cpp
[mod] : unkowncommand foramt, quit ==0
=> [mod] : unkowncommand foramt, quit ==0

Channel.cpp
=> [Mod] fix kick bug

Server.cpp
- 클라이언트가 연결이 끊긴 후 invite list에 남아있는 문제를 해결
=> [Mod]invite list 에서 지워주기

Channel.cpp, Channel.hpp
=> [Add] add Channel::changeInviteNick()

Channel.cpp, Channel.hpp, Command.cpp
- Channel PART 구현
- INVITE 전체적으로 수정
=> [Mod, Add] INVITE, PART

Command.cpp, handleresponse.cpp
[Mod] : add the reason for Command::part[Mod] : add the reason for Command::part[Mod] : add the reason for Command::part[Mod] : add the reason for Command::part[Mod] : add the reason for Command::part[Mod] : add the reason for Command::part[Mod] : add the reason for Command::part[Mod] : add the reason for Command::part
=> [Mod] : add the reason for Command::part

Client.cpp, Client.hpp, Server.cpp, Server.hpp, main.cpp
=> [Mod] 현준님 예방주사

Bonus.cpp, Channel.cpp, Client.cpp, Client.hpp, Command.cpp, Command.hpp, Server.cpp
=> [Mod] 불필요한 부분 제거

Channel.cpp, Command.cpp
part에 에러 사항 리턴 추가하고 Command::join 에 continue 안된거 추가함 채널명이 #인 채널 안될줄 알았는데 확인해보니까 돼서 되게끔 다시 수정
=> Junhylee : [Mod] : Channel::part, Command::join
